In [14]:
#21-sep-2022
x=[1,2],[8,4]
y=[1,2],[3,4]

z=[]
for i in range(2):
    for j in range(2):
        print(i,j)

0 0
0 1
1 0
1 1


In [2]:
x=[1,2],[3,4]
y=[1,2],[3,4]

z=[]
for i in range(2):
    for j in range(2):
        ans=x[i][j]+y[i][j]
        print(ans)

2
4
6
8


In [ ]:
x=[1,2],[9,4]
y=[1,2],[3,4]

z=[]
for i in range(2):
    for j in range(2):
        ans=x[i][j]+y[i][j]
        print(ans)

In [2]:
!pip show numpy


Name: numpy
Version: 1.23.1
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: c:\users\shiva\miniconda3\lib\site-packages
Requires: 
Required-by: pgzero, pandas


In [4]:
#ndarray
type(x)

tuple

In [17]:
from turtle import shape
#24 sep 2022

import numpy as np
x=[[1,2],[4,7]]
y=[[2,3],[4,7]]
nx=np.array(x)
ny=np.array(y)
print(nx)
print(ny)
print("matrix shape",nx.shape)


[[1 2]
 [4 7]]
[[2 3]
 [4 7]]
matrix shape (2, 2)


In [18]:
nx + ny

array([[ 3,  5],
       [ 8, 14]])

In [19]:
#add 5 in all
nx+5

array([[ 6,  7],
       [ 9, 12]])

In [22]:
np.arange(10) #0 to 19

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a=np.arange(-10,10,.01)
print(a)
print(a.shape)
print(a.dtype)


[-10.    -9.99  -9.98 ...   9.97   9.98   9.99]
(2000,)
float64


In [27]:
b=np.linspace(1,100,225,dtype=int)
print(b)
print(b.shape)
b.reshape(15,15)


[  1   1   1   2   2   3   3   4   4   4   5   5   6   6   7   7   8   8
   8   9   9  10  10  11  11  12  12  12  13  13  14  14  15  15  16  16
  16  17  17  18  18  19  19  20  20  20  21  21  22  22  23  23  23  24
  24  25  25  26  26  27  27  27  28  28  29  29  30  30  31  31  31  32
  32  33  33  34  34  35  35  35  36  36  37  37  38  38  39  39  39  40
  40  41  41  42  42  42  43  43  44  44  45  45  46  46  46  47  47  48
  48  49  49  50  50  50  51  51  52  52  53  53  54  54  54  55  55  56
  56  57  57  58  58  58  59  59  60  60  61  61  61  62  62  63  63  64
  64  65  65  65  66  66  67  67  68  68  69  69  69  70  70  71  71  72
  72  73  73  73  74  74  75  75  76  76  77  77  77  78  78  79  79  80
  80  80  81  81  82  82  83  83  84  84  84  85  85  86  86  87  87  88
  88  88  89  89  90  90  91  91  92  92  92  93  93  94  94  95  95  96
  96  96  97  97  98  98  99  99 100]
(225,)


array([[  1,   1,   1,   2,   2,   3,   3,   4,   4,   4,   5,   5,   6,
          6,   7],
       [  7,   8,   8,   8,   9,   9,  10,  10,  11,  11,  12,  12,  12,
         13,  13],
       [ 14,  14,  15,  15,  16,  16,  16,  17,  17,  18,  18,  19,  19,
         20,  20],
       [ 20,  21,  21,  22,  22,  23,  23,  23,  24,  24,  25,  25,  26,
         26,  27],
       [ 27,  27,  28,  28,  29,  29,  30,  30,  31,  31,  31,  32,  32,
         33,  33],
       [ 34,  34,  35,  35,  35,  36,  36,  37,  37,  38,  38,  39,  39,
         39,  40],
       [ 40,  41,  41,  42,  42,  42,  43,  43,  44,  44,  45,  45,  46,
         46,  46],
       [ 47,  47,  48,  48,  49,  49,  50,  50,  50,  51,  51,  52,  52,
         53,  53],
       [ 54,  54,  54,  55,  55,  56,  56,  57,  57,  58,  58,  58,  59,
         59,  60],
       [ 60,  61,  61,  61,  62,  62,  63,  63,  64,  64,  65,  65,  65,
         66,  66],
       [ 67,  67,  68,  68,  69,  69,  69,  70,  70,  71,  71,  72,  72,
       

In [28]:
b.reshape(3,5,5,3)#4d array

array([[[[  1,   1,   1],
         [  2,   2,   3],
         [  3,   4,   4],
         [  4,   5,   5],
         [  6,   6,   7]],

        [[  7,   8,   8],
         [  8,   9,   9],
         [ 10,  10,  11],
         [ 11,  12,  12],
         [ 12,  13,  13]],

        [[ 14,  14,  15],
         [ 15,  16,  16],
         [ 16,  17,  17],
         [ 18,  18,  19],
         [ 19,  20,  20]],

        [[ 20,  21,  21],
         [ 22,  22,  23],
         [ 23,  23,  24],
         [ 24,  25,  25],
         [ 26,  26,  27]],

        [[ 27,  27,  28],
         [ 28,  29,  29],
         [ 30,  30,  31],
         [ 31,  31,  32],
         [ 32,  33,  33]]],


       [[[ 34,  34,  35],
         [ 35,  35,  36],
         [ 36,  37,  37],
         [ 38,  38,  39],
         [ 39,  39,  40]],

        [[ 40,  41,  41],
         [ 42,  42,  42],
         [ 43,  43,  44],
         [ 44,  45,  45],
         [ 46,  46,  46]],

        [[ 47,  47,  48],
         [ 48,  49,  49],
         [ 50,  50,  5

In [29]:
np.random.rand(3,3)#random any number

array([[0.84274543, 0.18787181, 0.80462945],
       [0.00561397, 0.25772179, 0.33885922],
       [0.16341681, 0.44087882, 0.7217252 ]])

In [31]:
np.random.randint(1,100,size=(3,3))#randok inmtegr bw 1 to 100

array([[16, 94, 20],
       [36, 24, 64],
       [54, 51, 72]])

In [36]:
from random import random
x=np.random.randint(1,10,100)
print(x)
print('first element:',x[0])
print('last element:',x[-1])
print('first  6 element:',x[:6])
print('last  6 element:',x[-6:])

[3 6 2 5 6 4 2 6 4 6 3 2 5 1 6 1 8 9 2 8 5 4 6 5 8 5 3 1 9 2 8 9 6 7 9 3 5
 7 2 4 6 9 4 2 8 5 9 6 7 7 1 5 9 2 5 2 8 1 5 8 1 2 6 8 9 6 7 6 6 1 8 8 6 5
 4 7 2 8 7 4 4 7 3 4 6 3 4 5 1 9 9 3 2 2 3 2 3 8 5 8]
first element: 3
last element: 8
first  6 element: [3 6 2 5 6 4]
last  6 element: [3 2 3 8 5 8]


#for 2d matrix 
- single row=array[row,coloumn]
----
-single row=array[row]
----
single coloumn=array[:,column] 
----
multiple row=array[row1:row2]
----
multiple columns=array[:,column1:column2]
----
multiple row and column=array[row1:row2,column1:column2]

In [49]:
x2=x.reshape(10,10)
print(x2)
print('first element :',x2[0,0],'or',x2[0][0])
print('last element :',x2[-1,-1],'or',x2[-1][-1])
print('first row :',x2[0])
print('last row :',x2[-1])
print('first column :',x2[:,0])
print('last column :',x2[:,-1])
print('3rd row',x2[2])
print('3rd column',x2[:,2])
print('fist 3 row and 3 column',x2[:3,:3])

[[3 6 2 5 6 4 2 6 4 6]
 [3 2 5 1 6 1 8 9 2 8]
 [5 4 6 5 8 5 3 1 9 2]
 [8 9 6 7 9 3 5 7 2 4]
 [6 9 4 2 8 5 9 6 7 7]
 [1 5 9 2 5 2 8 1 5 8]
 [1 2 6 8 9 6 7 6 6 1]
 [8 8 6 5 4 7 2 8 7 4]
 [4 7 3 4 6 3 4 5 1 9]
 [9 3 2 2 3 2 3 8 5 8]]
first element : 3 or 3
last element : 8 or 8
first row : [3 6 2 5 6 4 2 6 4 6]
last row : [9 3 2 2 3 2 3 8 5 8]
first column : [3 3 5 8 6 1 1 8 4 9]
last column : [6 8 2 4 7 8 1 4 9 8]
3rd row [5 4 6 5 8 5 3 1 9 2]
3rd column [2 5 6 6 4 9 6 6 3 2]
fist 3 row and 3 column [[3 6 2]
 [3 2 5]
 [5 4 6]]


In [61]:
y=np.random.randint(1,1000,(10,10))
print(y)

[[920  28 744 494 270 778 102 866 719 602]
 [361  92 247  40 480 851 650 523 508 715]
 [ 82 944 814 752 981  90  70 768 195 628]
 [256 845 965  94 526 153 196 158 318 875]
 [147 398 165 126 155 287 335 682 880 109]
 [831 231  46 145 532 541 180 603 589 415]
 [580 251 474  57 937 398 269 319 124 924]
 [636 218 236 191 763 958 816 510 447  45]
 [340 909 336 645 921 842 564 978 456  90]
 [513 669 186 835 119 783 644 291 848 649]]


In [57]:
for i in y:
    for j in i:
        if j< 500:
            print(j,end=' ')

            #or
           
y[y<500]#boolean 

75 193 205 485 430 187 221 39 91 403 31 474 28 400 235 378 397 382 39 356 70 222 204 286 28 434 374 118 479 187 69 115 44 479 18 416 160 493 40 127 459 18 477 111 280 165 251 311 197 112 330 440 

array([ 75, 193, 205, 485, 430, 187, 221,  39,  91, 403,  31, 474,  28,
       400, 235, 378, 397, 382,  39, 356,  70, 222, 204, 286,  28, 434,
       374, 118, 479, 187,  69, 115,  44, 479,  18, 416, 160, 493,  40,
       127, 459,  18, 477, 111, 280, 165, 251, 311, 197, 112, 330, 440])

In [58]:
y[(y>250) & (y<750)]#bitwise and is used

array([485, 672, 708, 430, 679, 584, 536, 403, 474, 400, 598, 378, 397,
       615, 536, 382, 603, 356, 501, 655, 286, 512, 434, 374, 479, 479,
       620, 416, 493, 630, 459, 477, 280, 547, 525, 251, 311, 592, 690,
       330, 540, 591, 506, 574, 440, 532, 505])

In [63]:
print('sum of all values:',y.sum())
print('sum of each row:',y.sum(axis=1))
print('sum of each column:',y.sum(axis=0))
print('----------------------------------')


print('mean of all values:',y.mean())
print('mean of each row:',y.mean(axis=1))
print('mean of each column',y.mean(axis=0))
print("-------------------------------------")
print("standard deviation of all values",y.std())
print("standard deviation of each row",y.std(axis=1))
print("standard deviation of each column",y.std(axis=0))
print('----------------------------------')

print("min and max of all values",y.min(),y.max())
print("min and max of each row",y.min(axis=1),y.max(axis=1))
print("min and max of each column",y.min(axis=0),y.max(axis=0))

sum of all values: 47868
sum of each row: [5523 4467 5324 4386 3284 4113 4333 4820 6081 5537]
sum of each column: [4666 4585 4213 3379 5684 5681 3826 5698 5084 5052]
----------------------------------
mean of all values: 478.68
mean of each row: [552.3 446.7 532.4 438.6 328.4 411.3 433.3 482.  608.1 553.7]
mean of each column [466.6 458.5 421.3 337.9 568.4 568.1 382.6 569.8 508.4 505.2]
-------------------------------------
standard deviation of all values 296.68187946013825
standard deviation of each row [302.04504631 250.18075466 359.03431591 320.33363857 247.92587602
 237.95926122 288.00765615 291.32112865 286.49029652 253.70969631]
standard deviation of each column [265.26597973 332.91417813 298.43493428 294.63416299 306.7801167
 301.14596129 250.61252961 249.66209164 243.51886991 308.31406066]
----------------------------------
min and max of all values 28 981
min and max of each row [ 28  40  70  94 109  46  57  45  90 119] [920 851 981 965 880 831 937 958 978 848]
min and max of

In [2]:
print(plt.style.available)
plt.style.use('tableau-colorblind10')

['Solarize_Light2', '_classic_test_patch', '_mpl-gallery', '_mpl-gallery-nogrid', 'bmh', 'classic', 'dark_background', 'fast', 'fivethirtyeight', 'ggplot', 'grayscale', 'seaborn-v0_8', 'seaborn-v0_8-bright', 'seaborn-v0_8-colorblind', 'seaborn-v0_8-dark', 'seaborn-v0_8-dark-palette', 'seaborn-v0_8-darkgrid', 'seaborn-v0_8-deep', 'seaborn-v0_8-muted', 'seaborn-v0_8-notebook', 'seaborn-v0_8-paper', 'seaborn-v0_8-pastel', 'seaborn-v0_8-poster', 'seaborn-v0_8-talk', 'seaborn-v0_8-ticks', 'seaborn-v0_8-white', 'seaborn-v0_8-whitegrid', 'tableau-colorblind10']


In [5]:
#from cProfile import label
import matplotlib.pyplot as plt
plt.figure(figsize=(10,20))

t=np.linspace(0,4*np.pi,50)
x=np.sin(t)
y=np.cos(t)
z=np.tan(t)
plt.plot(t,x,label='sin(t)',color='green',linewidth=3,marker='o',markersize=10)
plt.plot(t,y,label='cos(y)',color='hotpink',linewidth=3,marker='2',linestyle='--')
plt.text(10,0.5,'sin(t)',fontsize=20)
plt.text(7,0.5,'cos(t)',fontsize=20)
plt.legend()
plt.plot(t,z)
plt.grid(False)

NameError: name 'np' is not defined

<Figure size 720x1440 with 0 Axes>

import matplotlib.pyplot as plt